version: '3.7'

services:

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    container_name: frontend
    build:
      context: ./mjs-front-end
    environment:
      NODE_ENV: production
    depends_on:
      - backend
  
  backend:
    container_name: backend
    build:
      context: ./back-end
    environment:
      NODE_ENV: production
      DATABASE_USER: docker
      DATABASE_HOST: db
      DATABASE_DB: polls
      DATABASE_PASSWORD: docker
      DATABASE_PORT: 5432
    depends_on:
      - db

  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: