version: '3.7'

services:

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
      - db
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'

  frontend:
    container_name: frontend
    build:
      context: ./mjs-front-end
    environment:
      NODE_ENV: production
      VITE_BACKEND_API: api
    depends_on:
      - backend
      - db
  
  backend:
    container_name: backend
    build:
      context: ./back-end
    environment:
      NODE_ENV: production
      DATABASE_USER: docker
      DATABASE_HOST: db
      DATABASE_DB: polls
      DATABASE_PASSWORD: docker
      DATABASE_PORT: 5432
      DATABASE_URL: postgresql://docker:docker@db:5432/polls
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run start:prod"

  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=polls
    volumes:
      - /DATA/AppData/mjs-storemgm-sys/data/postgres:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d polls"]
      interval: 5s
      timeout: 5s
      retries: 10